// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyManagement.API.Data;

#nullable disable

namespace PropertyManagement.API.Migrations
{
    [DbContext(typeof(PMDbContext))]
    [Migration("20251113170532_Seed data for user")]
    partial class Seeddataforuser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyManagement.API.Models.Domain.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Balcony")
                        .HasColumnType("bit");

                    b.Property<string>("BathroomImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedroomImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("int");

                    b.Property<float>("CarpetAreaSqft")
                        .HasColumnType("real");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HallImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KitchenImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfRooms")
                        .HasColumnType("int");

                    b.Property<bool>("Parking")
                        .HasColumnType("bit");

                    b.Property<string>("ParkingImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9c77c44-6b82-4f60-8c74-2d5104696753"),
                            Email = "user@user.com",
                            FullName = "user"
                        });
                });

            modelBuilder.Entity("PropertyManagement.API.Models.Domain.Property", b =>
                {
                    b.HasOne("PropertyManagement.API.Models.Domain.User", "User")
                        .WithOne("Property")
                        .HasForeignKey("PropertyManagement.API.Models.Domain.Property", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PropertyManagement.API.Models.Domain.User", b =>
                {
                    b.Navigation("Property")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
